### PR TITLE
workflows added

### PR DESCRIPTION
**Pull request by Aviksaikat**
## Summary

These workflows are added 

## Issue
#1 

## Description

```sh
{{cookiecutter.project_slug}}/.github/
├── dependabot.yml
├── labels.yml
├── release-drafter.yml
└── workflows
    ├── build.yml
    ├── documentation.yml
    ├── draft.yml
    ├── labeler.yml
    └── tests.yml
```

### CODE REVIEW

**Comment by FlorianWilhelm** [comment]
Thanks @Aviksaikat! If you want to, you can directly add you to `AUTHORS.md`. 

Do you think Github Workflows should be always created or should we ask the user for it?

**Comment by Aviksaikat** [comment]
I like to add them by default. But that's my point of view. It would be complex to ask the user from the template. If they choose no, the workflow file will still be created but empty unless we find a better way to handle that case. 

I use `rye` or `UV` for small projects without workflows to manage the `virtual environment`. So it's better to be well-structured & with all the best practices if you're looking for a badass template on GitHub. If not then use the tools normally. What do you think?

**Comment by FlorianWilhelm** [comment]
I agree, so let's merge this.

**Comment by FlorianWilhelm** [comment]
... and thank you!

**Pull request merged**
